name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./app/gradlew

      - name: Build and run tests
        working-directory: ./app
        run: ./gradlew build --no-daemon

      - name: Run Checkstyle
        working-directory: ./app
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon
